[package]
name = "guest_json_cmp"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.3", default-features = false, features = ['std'] }
json = "0.12"
json-core = {path = "../../core"}
