[package]
name = "garbling-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = "2.1.1"
# risc0-build = { path = "../../../risc0/build" }

[package.metadata.risc0]
methods = ["guest"]
